### ISSUE TITLE
Error during model fitting

### ISSUE THREAD

**Issue by thatcadguy** [kitzeslab/opensoundscape#115]
Hi all, trying to run this on Ubuntu 18.04 LTS under WSL. Since instructions are for Mac, did this first:

```
sudo apt install libsamplerate-dev mongodb git wget
pip3 install pandas numpy matplotlib docopt scipy scikit-image pymongo progressbar2 pytest opencv-python scikit-learn
pip3 install git+git://github.com/gregorias/samplerate@master
mkdir -p ~/data/db
sudo mongod --dbpath ~/data/db
```

which gave me everything I need I believe, then edited opso-test-small.ini to reflect my absolute path to the dataset, proceeded as normal:

```
jake@Jake-Prec3530:~/opensoundscape$ python3 opensoundscape.py init -i opso-test-small.ini
jake@Jake-Prec3530:~/opensoundscape$ python3 opensoundscape.py spect_gen -i opso-test-small.ini > spect-gen-output-small.txt
jake@Jake-Prec3530:~/opensoundscape$ python3 opensoundscape.py model_fit -i opso-test-small.ini > model-fit-output-small.txt
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/jake/opensoundscape/modules/model_fit_algo/lasseck2013/model_fit_algo.py", line 417, in chunk_build_model
    results = [build_model(col, labels_df, config) for col in chunk]
  File "/home/jake/opensoundscape/modules/model_fit_algo/lasseck2013/model_fit_algo.py", line 417, in <listcomp>
    results = [build_model(col, labels_df, config) for col in chunk]
  File "/home/jake/opensoundscape/modules/model_fit_algo/lasseck2013/model_fit_algo.py", line 440, in build_model
    X, y = build_X_y(labels_df[column], config)
  File "/home/jake/opensoundscape/modules/model_fit_algo/lasseck2013/model_fit_algo.py", line 315, in build_X_y
    range(len(file_file_stats[o_idx]))])
TypeError: object of type 'NoneType' has no len()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "opensoundscape.py", line 54, in <module>
    model_fit(config, arguments['--rerun_statistics'])
  File "/home/jake/opensoundscape/modules/model_fit.py", line 31, in model_fit
    model_fit_algo(config, rerun_statistics)
  File "/home/jake/opensoundscape/modules/model_fit_algo/lasseck2013/model_fit_algo.py", line 485, in model_fit_algo
    for ret in executor.map(chunk_build_model, chunks, repeat(labels_df), repeat(config)):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: object of type 'NoneType' has no len()
jake@Jake-Prec3530:~/opensoundscape$
```

Any ideas? No visible error messages in my mongod terminal, looks like normal db operations. Python stuff for ref:

```
jake@Jake-Prec3530:~/opensoundscape$ python3 --version
Python 3.6.9
jake@Jake-Prec3530:~/opensoundscape$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
attrs (19.3.0)
audioread (2.1.8)
Automat (0.6.0)
blinker (1.4)
certifi (2020.4.5.1)
cffi (1.14.0)
chardet (3.0.4)
click (6.7)
cloud-init (19.4)
colorama (0.4.3)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.1.4)
cycler (0.10.0)
decorator (4.4.2)
distro-info (0.18ubuntu0.18.04.1)
docopt (0.6.2)
future (0.18.2)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.9)
imageio (2.8.0)
importlib-metadata (1.6.0)
incremental (16.10.1)
Jinja2 (2.10)
joblib (0.15.1)
jsonpatch (1.16)
jsonpointer (1.10)
jsonschema (2.6.0)
keyring (10.6.0)
keyrings.alt (3.0)
kiwisolver (1.2.0)
language-selector (0.1)
Lasagne (0.2.dev1)
librosa (0.7.2)
llvmlite (0.32.1)
MarkupSafe (1.0)
matplotlib (3.2.1)
more-itertools (8.3.0)
netifaces (0.10.4)
networkx (2.4)
numba (0.49.1)
numpy (1.18.4)
oauthlib (2.0.6)
opencv-python (4.2.0.34)
packaging (20.4)
PAM (0.4.2)
pandas (1.0.3)
Pillow (7.1.2)
pip (9.0.1)
pluggy (0.13.1)
progressbar2 (3.51.3)
py (1.8.1)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycparser (2.20)
pycrypto (2.6.1)
pygobject (3.26.1)
PyJWT (1.5.3)
pymongo (3.10.1)
pyOpenSSL (17.5.0)
pyparsing (2.4.7)
pyserial (3.4)
pytest (5.4.2)
python-apt (1.6.5+ubuntu0.2)
python-dateutil (2.8.1)
python-debian (0.1.32)
python-utils (2.4.0)
pytz (2020.1)
PyWavelets (1.1.1)
pyxdg (0.25)
PyYAML (3.12)
requests (2.23.0)
requests-unixsocket (0.1.5)
resampy (0.2.2)
scikit-image (0.17.2)
scikit-learn (0.23.1)
scikits.samplerate (0.4.0.dev0)
scipy (1.4.1)
SecretStorage (2.3.1)
service-identity (16.0.0)
setuptools (46.4.0)
six (1.15.0)
SoundFile (0.10.3.post1)
ssh-import-id (5.7)
systemd-python (234)
Theano (1.0.4)
threadpoolctl (2.0.0)
tifffile (2020.5.25)
Twisted (17.9.0)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.25.9)
wcwidth (0.1.9)
wheel (0.30.0)
zipp (3.1.0)
zope.interface (4.3.2)
jake@Jake-Prec3530:~/opensoundscape$
```

Any help would be appreciated, thanks all.

**Comment by jkitzes** [comment]
Thanks for the pointer. Ironically, we were just about to turn over a totally new release. You can find it now in `master`, maybe see if that works for your use case. Alternatively, we just merged a bunch of bug fixes into what is now `deprecated_master`, which has the same interface as what you were looking at before.

**Comment by thatcadguy** [comment]
Awesome thanks!
