### ISSUE TITLE
Error checking in `SingleTargetAudioDataset`

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#236]
Errors while loading some audio files during training. Need to figure out what's wrong with this! In the meantime, might want to add some simple try/except error checking in `SingleTargetAudioDataset`, possibly a flag.

Full tracebacks from log file:

```
2020-09-03_17:18:25EDT: Traceback (most recent call last):

2020-09-03_17:18:25EDT:   File "geothlypis-trichas-256.py", line 153, in <module>

2020-09-03_17:18:25EDT:
2020-09-03_17:18:25EDT: save_scores=True,
2020-09-03_17:18:25EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/opensoundscape/torch/train.py", line 165, in train

2020-09-03_17:18:25EDT:
2020-09-03_17:18:25EDT: for t in valid_loader:
2020-09-03_17:18:25EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__

2020-09-03_17:18:25EDT:
2020-09-03_17:18:25EDT: data = self._next_data()
2020-09-03_17:18:25EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data

2020-09-03_17:18:25EDT:
2020-09-03_17:18:25EDT: return self._process_data(data)
2020-09-03_17:18:25EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data

2020-09-03_17:18:25EDT:
2020-09-03_17:18:25EDT: data.reraise()
2020-09-03_17:18:25EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise

2020-09-03_17:18:25EDT:
2020-09-03_17:18:25EDT: raise self.exc_type(msg)
2020-09-03_17:18:25EDT: OSError
2020-09-03_17:18:25EDT: :
2020-09-03_17:18:25EDT: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/librosa/core/audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/bgfs/jkitzes/xeno-canto-split/calidris-canutus/23892-30.0s-36.0s.mp3': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/opensoundscape/datasets.py", line 438, in __getitem__
    audio = Audio.from_file(audio_path, sample_rate=self.audio_sample_rate)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/opensoundscape/audio.py", line 86, in from_file
    path, sr=sample_rate, res_type=resample_type, mono=True
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/librosa/core/audio.py", line 162, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/librosa/core/audio.py", line 186, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/audioread/__init__.py", line 107, in audio_open
    backends = available_backends()
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/audioread/__init__.py", line 76, in available_backends
    if _gst_available():
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/audioread/__init__.py", line 27, in _gst_available
    import gi
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
OSError: [Errno 70] Communication error on send: '/bgfs/jkitzes/ter38/song3/14_batch_size_experiment/batch/geothlypis-trichas-256'
```

```
2020-09-03_17:17:52EDT: Traceback (most recent call last):

2020-09-03_17:17:52EDT:   File "hylocichla-mustelina-256.py", line 153, in <module>

2020-09-03_17:17:52EDT:
2020-09-03_17:17:52EDT: save_scores=True,
2020-09-03_17:17:52EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/opensoundscape/torch/train.py", line 165, in train

2020-09-03_17:17:52EDT:
2020-09-03_17:17:52EDT: for t in valid_loader:
2020-09-03_17:17:52EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__

2020-09-03_17:17:52EDT:
2020-09-03_17:17:52EDT: data = self._next_data()
2020-09-03_17:17:52EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data

2020-09-03_17:17:52EDT:
2020-09-03_17:17:52EDT: return self._process_data(data)
2020-09-03_17:17:52EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data

2020-09-03_17:17:52EDT:
2020-09-03_17:17:52EDT: data.reraise()
2020-09-03_17:17:52EDT:   File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise

2020-09-03_17:17:52EDT:
2020-09-03_17:17:52EDT: raise self.exc_type(msg)
2020-09-03_17:17:52EDT: OSError
2020-09-03_17:17:52EDT: :
2020-09-03_17:17:52EDT: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/librosa/core/audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/bgfs/jkitzes/xeno-canto-split/aegolius-funereus/217714-6.0s-12.0s.mp3': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/opensoundscape/datasets.py", line 438, in __getitem__
    audio = Audio.from_file(audio_path, sample_rate=self.audio_sample_rate)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/opensoundscape/audio.py", line 86, in from_file
    path, sr=sample_rate, res_type=resample_type, mono=True
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/librosa/core/audio.py", line 162, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/librosa/core/audio.py", line 186, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/audioread/__init__.py", line 107, in audio_open
    backends = available_backends()
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/audioread/__init__.py", line 76, in available_backends
    if _gst_available():
  File "/ihome/jkitzes/ter38/.virtualenvs/opso_dev/lib/python3.7/site-packages/audioread/__init__.py", line 27, in _gst_available
    import gi
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
OSError: [Errno 70] Communication error on send: '/bgfs/jkitzes/ter38/song3/14_batch_size_experiment/batch/hylocichla-mustelina-256'
```

**Comment by sammlapp** [comment]
see #270 for new architecture
