### ISSUE TITLE
update_labels=True causes error in training

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#392]
Update labels is not working properly in OverlayImage action, error message:

```

2021-11-09_07:24:12EST: x, df_row = action.go(x, copy.deepcopy(df_row))
2021-11-09_07:24:12EST:   File "/jet/home/sammlapp/.cache/pypoetry/virtualenvs/opensoundscape-avXCDjS8-py3.8/lib/python3.8/site-packages/opensoundscape/preprocess/actions.py", line 700, in go
2021-11-09_07:24:12EST: x_labels.values[:] = np.logical_or(
2021-11-09_07:24:12EST: ValueError
2021-11-09_07:24:12EST: :
2021-11-09_07:24:12EST: could not broadcast input array from shape (2,48) into shape (48,)
2021-11-09_07:24:12EST:
2021-11-09_07:24:12EST: During handling of the above exception, another exception occurred:
2021-11-09_07:24:12EST: Traceback (most recent call last):
2021-11-09_07:24:12EST:   File "train.py", line 91, in <module>
2021-11-09_07:24:12EST: print(f"Shape of train_dataset[0]['X']: {train_dataset[0]['X'].shape}")
2021-11-09_07:24:12EST:   File "/jet/home/sammlapp/.cache/pypoetry/virtualenvs/opensoundscape-avXCDjS8-py3.8/lib/python3.8/site-packages/opensoundscape/preprocess/preprocessors.py", line 80, in __getitem__
2021-11-09_07:24:12EST: raise PreprocessingError(
2021-11-09_07:24:12EST: opensoundscape.preprocess.utils
2021-11-09_07:24:12EST: .
2021-11-09_07:24:12EST: PreprocessingError
```

**Comment by sammlapp** [comment]
this was occuring when overlay_df had a duplicated index. When accessing the labels, a 2-dimensional array was returned. 

I did two things: 

1) added assertion of unique index when creating ImgOverlay actions

2) added line in CnnPreprocessor that removes duplicate indices in overlay_df. It's silent and could trick a user who intended to pass a df with a duplicated index.
