### ISSUE TITLE
add missing modules to docs

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#395]
at least the `audiomoth` and `signal` modules are missing from docs. We should add to our release protocol to check docs for missing/out of date modules, if its not already there. Actually, I think we were going to switch to something more automatic for having all modules in the docs.

**Comment by sammlapp** [comment]
@jkitzes autodoc is failing to import one module (something related to `import pywt` when trying to create docs for the signal module.) Not sure how to even begin debugging it, because I don't understand where the error comes from. To reproduce:

checkout 

build the docs:
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html 

The section in the docs for `signal.py` is empty, and the output contains this error: 
```
WARNING: autodoc: failed to import module 'signal' from module 'opensoundscape'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/SML161/opt/miniconda3/envs/opso/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/Users/SML161/opt/miniconda3/envs/opso/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/SML161/opensoundscape/opensoundscape/signal.py", line 5, in <module>
    import pywt
  File "/Users/SML161/opt/miniconda3/envs/opso/lib/python3.7/site-packages/pywt/__init__.py", line 16, in <module>
    from ._extensions._pywt import *
  File "__init__.pxd", line 206, in init pywt._extensions._pywt
TypeError: numpy.dtype is not a type object

```

**Comment by jkitzes** [comment]
@sammlapp I suspect a version conflict. Is this failing on your local machine, not on `readthedocs`? I think we _might_ try merging into `develop` and seeing if it builds remotely.
