### ISSUE TITLE
cuda device issues

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#438]
Louis:
(A) the fresh environment in 0.6.1 on bridges2: in loss calculation, one tensor is on cuda one on CPU
- was not specifying a device
- tried to specify a device as well

(B) Potentially separate issue: model not(?) using GPU both 0.6.0 and 0.6.1 - bridges and snowy
- GPU memory was filling up, but no GPU usage

Lauren:
Expected all tensors on same device, found 2 devices cuda and CPU
- up to date develop branch 
- did not explicitly change device

**Comment by lmc150** [comment]
Error message I received:
`2022-01-07_17:05:21EST: Traceback (most recent call last):
2022-01-07_17:05:21EST:   File "train.py", line 120, in <module>
2022-01-07_17:05:21EST: model.train(
2022-01-07_17:05:21EST:   File "/jet/home/lmc150/opensoundscape/opensoundscape/torch/models/cnn.py", line 395, in train
2022-01-07_17:05:21EST: train_targets, train_preds, train_scores = self.train_epoch()
2022-01-07_17:05:21EST:   File "/jet/home/lmc150/opensoundscape/opensoundscape/torch/models/cnn.py", line 272, in train_epoch
2022-01-07_17:05:21EST: loss = self.loss_fn(logits, batch_labels)
2022-01-07_17:05:21EST:   File "/jet/home/lmc150/.conda/envs/opso-dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
2022-01-07_17:05:21EST: return forward_call(*input, **kwargs)
2022-01-07_17:05:21EST:   File "/jet/home/lmc150/opensoundscape/opensoundscape/torch/loss.py", line 156, in forward
2022-01-07_17:05:21EST: weight = self.reweight_functions(label)
2022-01-07_17:05:21EST:   File "/jet/home/lmc150/opensoundscape/opensoundscape/torch/loss.py", line 167, in reweight_functions
2022-01-07_17:05:21EST: weight = self.rebalance_weight(label.float())
2022-01-07_17:05:21EST:   File "/jet/home/lmc150/opensoundscape/opensoundscape/torch/loss.py", line 177, in rebalance_weight
2022-01-07_17:05:21EST: repeat_rate = torch.sum(gt_labels.float() * self.freq_inv, dim=1, keepdim=True)
2022-01-07_17:05:21EST: RuntimeError
2022-01-07_17:05:21EST: :
2022-01-07_17:05:21EST: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

**Comment by louisfh** [comment]
I got the same error as Lauren, using a fresh conda environment with Opensoundscape 0.6.1 pip-installed from Pypi. 
```
File "train_high_freq.py", line 108, in <module>
  log_interval=10 #batches
 File "/jet/home/louisfh/opensoundscape/opensoundscape/torch/models/cnn.py", line 395, in train
  train_targets, train_preds, train_scores = self.train_epoch()
 File "/jet/home/louisfh/opensoundscape/opensoundscape/torch/models/cnn.py", line 272, in train_epoch
  loss = self.loss_fn(logits, batch_labels)
 File "/jet/home/louisfh/.conda/envs/opso_poetry/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
  return forward_call(*input, **kwargs)
 File "/jet/home/louisfh/opensoundscape/opensoundscape/torch/loss.py", line 156, in forward
  weight = self.reweight_functions(label)
 File "/jet/home/louisfh/opensoundscape/opensoundscape/torch/loss.py", line 167, in reweight_functions
  weight = self.rebalance_weight(label.float())
 File "/jet/home/louisfh/opensoundscape/opensoundscape/torch/loss.py", line 177, in rebalance_weight
  repeat_rate = torch.sum(gt_labels.float() * self.freq_inv, dim=1, keepdim=True)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by louisfh** [comment]
Possible issue B):
On both Snowy and Bridges-2 I have tried training the same model using fresh environments with OpSo 0.6.0 installed using pip, and using poetry. In both these environments the model is very slow to train. On Snowy, `nvidia-smi` shows the GPU memory is being used, but does not show computation is happening. On Bridges-2 I have not actually checked GPU usage, but the model is training very slowly.

**Comment by sammlapp** [comment]
The issue (A) seems to arise from the ResampleLoss class, which takes in arguments that have the model's device and performs operations with other variables created internally - we probably just need to move these internal variables  like self.freq_inv  or self.class_freq to model.device, because they will be on CPU by default.

**Comment by sammlapp** [comment]
confirmed this by using PytorchModel instead of CnnResampleLoss - works fine

**Comment by sammlapp** [comment]
resolved in branch `issue_438_cuda` - try it out on bridges2 and snowy

**Comment by lmc150** [comment]
I am no longer encountering issue (A) on bridges 2 but I am now also noticing the same issue (B) as Louis. The difference is on a scale of hours.

**Comment by sammlapp** [comment]
Creating a separate issue for B, it is a different thing
