### ISSUE TITLE
Parallel predictions doesn't work on Windows computers 

### ISSUE THREAD

**Issue by lydiakatsis** [kitzeslab/opensoundscape#525]
Running predictions with num workers set to 1 or higher gives the following error on Windows computers:

![image](https://user-images.githubusercontent.com/72734966/185622559-1b9489ab-2dee-47af-ab7a-f4393bb7f41e.png)

**Comment by sammlapp** [comment]
Multiple workers on Windows seems to be a known issue with PyTorch, and apparently is solved in pytorch versions >=1.7.0 (https://github.com/pytorch/pytorch/issues/12831#issuecomment-1034086521) by using "persistent_workers=True" for a DataLoader. 

If this resolves the same issue @lydiakatsis has, a workaround for opensoundscape would be to override the CNN._init_dataloader method and specify ` persistent_workers=True`, for instance:

```
from opensoundscape.torch.models.cnn import CNN

class WindowsCNN(CNN):
    def _init_dataloader(
        self, safe_dataset, batch_size=64, num_workers=1, shuffle=False
    ):
        """initialize dataloader for training

        Override this function to use a different DataLoader or sampler
        """
        return DataLoader(
            safe_dataset,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=True,
            persistent_workers=True,
        )

model = WindowsCNN('resnet18',classes=[0,1],sample_duration = 2.0)
```

If this works, we can expose the `persistent_workers` option in the opensoundscape API or offer an alternative class or method for this use case.

**Comment by lydiakatsis** [comment]
Hi Sam - so I tried testing this -- not sure if I did this correctly - but I'm getting the following issue - here is my code:

`from opensoundscape.torch.models.cnn import CNN

class WindowsCNN(CNN):
    def _init_dataloader(
        self, safe_dataset, batch_size=64, num_workers=1, shuffle=False
    ):
        """initialize dataloader for training

        Override this function to use a different DataLoader or sampler
        """
        return DataLoader(
            safe_dataset,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=True,
            persistent_workers=True,
        )

model = WindowsCNN('resnet18',classes=[0,1],sample_duration = 4.0)

prediction_df =  glob('val/background/*.wav')  # make sure this sends us to where data is
#file_list = file_list[:1000] #comment out if not testing
audio_file_df = pd.DataFrame(index=prediction_df).head(10)


model.predict(audio_file_df ,binary_preds='single_target', num_workers = 2)

`

Error:

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [34], in <cell line: 1>()
----> 1 model.predict(audio_file_df ,binary_preds='single_target', num_workers = 2)

File ~\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\opensoundscape\torch\models\cnn.py:760, in CNN.predict(self, samples, batch_size, num_workers, activation_layer, binary_preds, threshold, split_files_into_clips, overlap_fraction, final_clip, bypass_augmentations, unsafe_samples_log)
    757 # disable gradient updates during inference
    758 with torch.set_grad_enabled(False):
--> 760     for batch in dataloader:
    761         # get batch of Tensors
    762         batch_tensors = batch["X"].to(self.device)
    763         batch_tensors.requires_grad = False

File ~\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\utils\data\dataloader.py:681, in _BaseDataLoaderIter.__next__(self)
    678 if self._sampler_iter is None:
    679     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    680     self._reset()  # type: ignore[call-arg]
--> 681 data = self._next_data()
    682 self._num_yielded += 1
    683 if self._dataset_kind == _DatasetKind.Iterable and \
    684         self._IterableDataset_len_called is not None and \
    685         self._num_yielded > self._IterableDataset_len_called:

File ~\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\utils\data\dataloader.py:1376, in _MultiProcessingDataLoaderIter._next_data(self)
   1374 else:
   1375     del self._task_info[idx]
-> 1376     return self._process_data(data)

File ~\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\utils\data\dataloader.py:1402, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1400 self._try_put_index()
   1401 if isinstance(data, ExceptionWrapper):
-> 1402     data.reraise()
   1403 return data

File ~\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\_utils.py:461, in ExceptionWrapper.reraise(self)
    457 except TypeError:
    458     # If the exception takes multiple arguments, don't try to
    459     # instantiate since we don't know how to
    460     raise RuntimeError(msg) from None
--> 461 raise exception

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\lydia\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\lydia\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lydia\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lydia\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\opensoundscape\torch\safe_dataset.py", line 171, in __getitem__
    raise IndexError("Tried all samples, none were safe")
IndexError: Tried all samples, none were safe`

**Comment by lydiakatsis** [comment]
Would it be possible to please give me an example of code I could test for loading a trained model and doing predictions using the WindowsCNN dataloader?

**Comment by sammlapp** [comment]
The code above works for me. The IndexError "Tried all samples, none were safe" means that every sample raised a PreprocessingError when the model tried to load it. You could try preprocessing a single sample to check what kind of error is occurring. 

```
from opensoundscape.torch.datasets import AudioFileDataset
dataset = AudioFileDataset(audio_file_df.index.values,model.preprocessor,return_labels=False)
print(audio_file_df.index.values[0])

#preprocess the first sample, check what kind of error is occuring
dataset[0]
```

It's possible that there is something specific to a Windows system going on here that I can't reproduce on my Mac. 

On a side note, your example above shows that it's hard to debug what's happening when all samples through PreprocessingErrors (you just see "IndexError: Tried all samples, none were safe") so I opened another issue #562 for improving the interpretability of this kind of error.

**Comment by sammlapp** [comment]
Can we try to reproduce this and see if the issue persists? @lydiakatsis have you continued to experience issues with parallelized prediction on windows?

**Comment by lydiakatsis** [comment]
@sammlapp I haven't continued working on a windows computer, but I will be needing to show Windows users how to run predictions early next year so a) I will be looking into it again, and b) lets try and fix it!!

**Comment by sammlapp** [comment]
I'm assuming this is fixed, new issues welcome for bugs in current opso version
