### ISSUE TITLE
SynchronizedRecorderArray.estimate_locations assumes names for the levels of the multi-index of the detections dataframe

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#712]
The method `check_missing_coordinates` of the `SynchronizedRecorderArray` class assumes that level 0 of the index of the detections dataframe is named 'files'. Here's the code:
```
def check_files_missing_coordinates(self, detections):
     523     files_missing_coordinates = []
---> 524     files = list(detections.reset_index()["file"].unique())
     525     for file in files:
     526         if str(file) not in self.file_coords.index:
```

This means if a user passes a `detections` dataframe that appears to be in the right format - i.e. with multi-index [file, start_time, end_time] and columns for the classes, an error will be thrown if the first level of the index is not explicitly called 'file'.

I think we should rewrite the code so that it assumes the first level of the multi-index is the files, but does not rely on it being explicitly named that. I think the output of `model.predict` does not explicitly name the first index 'files'. Alternatively if we want to enforce that, we should make clear to the user that the index levels must be named, and should also enforce this for any `clip_df` or `predictions_df` dataframes we use elsewhere in the code base.

**Comment by sammlapp** [comment]
I think I would prefer the enforcement of column names. Currently, the dataframe returned by `model.predict` will have an index matching `prediction_dataset` passed to it, but we don't enforce naming of the index.

**Comment by louisfh** [comment]
I noticed that `ML.datasets.AudioFileDataset` already has an assertion that tests this:
```
            assert list(df.index.names) == [
                "file",
                "start_time",
                "end_time",
            ], "multi-index must be ('file','start_time','end_time')"
```

I would prefer we drop the requirement for index names. 

However if we want to keep it, we should make sure we're consistent. There are a few places in the code/documentation where we say the multi-index must be 
`path, start_time, end_time` If we're going to enforce naming level 0 `file`, we should make sure we change these.

**Comment by louisfh** [comment]
The that one of the levels of the index is called "end_time" is also present.
https://github.com/kitzeslab/opensoundscape/blob/03e8661aab2a68e2d3e7737e3044b4d3ee3cb0ec/opensoundscape/localization.py#L605-L606C55

Posting here as a reminder for when the issue is addressed.

**Comment by louisfh** [comment]
I noticed this because I had the following traceback:
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pip_opso09_py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'end_time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/pip_opso09_py39/lib/python3.9/site-packages/opensoundscape/localization.py", line 473, in localize_detections
    candidate_events = self.create_candidate_events(
  File "/opt/anaconda3/envs/pip_opso09_py39/lib/python3.9/site-packages/opensoundscape/localization.py", line 606, in create_candidate_events
    clip_end = clip.reset_index()["end_time"].values[0]
  File "/opt/anaconda3/envs/pip_opso09_py39/lib/python3.9/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/anaconda3/envs/pip_opso09_py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'end_time'
```

Caused because the name was ` end_time`, instead of `end_time` (notice the leading space). This is an example of why I don't like requiring names. I think it can make these kinds of errors opaque.

**Comment by sammlapp** [comment]
The required names of the multi-index are well-documented throughout the codebase, so I think it's reasonable to enforce them
