### ISSUE TITLE
RuntimeError: Pin memory thread exited unexpectedly

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#726]
```
Traceback (most recent call last):
  File "/media/emu/misc/louisfh_seagate6copy/louisfh/NFCs/analysis/2023_05_12_predictions.py", line 26, in <module>
    scores = model.predict([f], batch_size = 64, num_workers = 16)
  File "/home/lfh/miniconda3/envs/opso_09_pip_py39/lib/python3.9/site-packages/opensoundscape/ml/cnn.py", line 1111, in predict
    for i, samples in enumerate(dataloader):
  File "/home/lfh/miniconda3/envs/opso_09_pip_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/lfh/miniconda3/envs/opso_09_pip_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/home/lfh/miniconda3/envs/opso_09_pip_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1290, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
```

Happens during inference on snowy (our ubuntu GPU machine) when batch_size is set too high.

----
Putting this in your code is a current workaround:
```
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')
```

the workaround also may resolve some other errors including 

`RuntimeError('received %d items of ancdata')` 

and  "too many open files"

**Comment by sammlapp** [comment]
This is bad! Is it associated with a specific version of opso, torch, or torchvision? Are there any related issues mentioned on torch GitHub?

**Comment by louisfh** [comment]
The environment that I encountered this in is a fresh python 3.9.16 environment where I ran`pip install opensoundscape==0.9.0`

Relevant packages from `pip list`

```
opensoundscape           0.9.0
torch                    2.0.0
torchvision              0.15.1
```

**Comment by sammlapp** [comment]
It would be great if we can make a reproducible example with just torch

**Comment by sammlapp** [comment]
may be worth upgrading to torchvision==0.15.2 and checking if the error still occurs, though I don't see any recent issues mentioning this error. 

Also, did you check if it happens for any batch_size>1 or only for large batch size?

**Comment by louisfh** [comment]
I tested this with a number of batch_sizes. It happened with 256, 128, 32 and 16. At that point I tried `batch_size = 1` and it worked. I will try to make a reproducible example and share.

**Comment by louisfh** [comment]
We tried again, and found that it fails with `batch_size=32, num_workers=16`. It may be num_workers and batch_size that are both involved (maybe it's total memory usage that causes the problem?). With `batch_size = 16, num_workers = 32)` I get a longer exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata
/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/opensoundscape/audio.py:338: UserWarning: Audio object is shorter than requested duration: 0.3 sec instead of 0.30000000000001137 sec
  warnings.warn(error_msg)
Traceback (most recent call last):
  File "/media/emu/misc/louisfh_seagate6copy/louisfh/NFCs/analysis/test_preds.py", line 26, in <module>
    scores = model.predict([f], batch_size = 16, num_workers = 32)
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/opensoundscape/ml/cnn.py", line 1111, in predict
    for i, samples in enumerate(dataloader):
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/lfh/miniconda3/envs/local_pip_install_py39/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1289, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
```

**Comment by louisfh** [comment]
Lauren has also run in to this error. She ended up training the model in 0.8 to avoid it.

A workaround could be to put this snippet at the top of your script.

```
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')
```

**Comment by sammlapp** [comment]
this workaround also resolved an error I got which read "Too many open files"

**Comment by louisfh** [comment]
Here's a still open issue in Pytorch that may be related: https://github.com/pytorch/pytorch/issues/91252

**Comment by sammlapp** [comment]
Apparently the "workaround" Louis mentioned above is actually the approach pytorch recommends, and this is "expected behavior"... so I guess we can hard-code the workaround into opso?
https://github.com/pytorch/pytorch/issues/11201#issuecomment-421146936

**Comment by sammlapp** [comment]
can we make our CI reproduce this error? We should add a test with large batch size. Also test if newest pytorch version still has this issue.

**Comment by sammlapp** [comment]
I decided to add the fix to `opensoundscape/ml/__init__.py` so that it always sets
```python
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')
``` 

we can revisit in the future if necessary
