### ISSUE TITLE
support Python 3.11 (eventually)

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#743]
Currently, Ray does not yet support python 3.11. But Ray shouldn't be a dependency (#744 ) so let's see if there are other issues with 3.11 when we remove it from pyproject.toml

**Comment by sammlapp** [comment]
its still fails, now with numba:
```
Collecting numba>=0.48.0
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/d8/265wdp1n0bn_r85dh3pp95fh0000gq/T/pip-install-63v2vqfe/numba_e1b7b9331be04309a2c5abb66db6482b/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/d8/265wdp1n0bn_r85dh3pp95fh0000gq/T/pip-install-63v2vqfe/numba_e1b7b9331be04309a2c5abb66db6482b/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
      [end of output]
```

**Comment by sammlapp** [comment]
it looks llke numba supports python 3.11 starting from Numba 0.57.0rc1 (https://github.com/numba/numba/issues/8841)

**Comment by sammlapp** [comment]
tests pass for Python 3.11 on develop 🎉  (ran them on my laptop, Apple Silicon. Not sure if we should add 3.11 to the CI yet)
