### ISSUE TITLE
wandb complains if you continue training a model

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#787]
wandb.watch gets called again, causing this error:

```
wandb: logging graph, to disable use `wandb.watch(log_graph=False)`
Traceback (most recent call last):
  File "/home/sml161/song8_nfwf_model/train_cont.py", line 16, in <module>
    m.train(train,test,num_workers=10,batch_size=128,epochs=20,wandb_session=wb,save_path='./run2')
  File "/home/sml161/miniconda3/envs/opso091/lib/python3.10/site-packages/opensoundscape/ml/cnn.py", line 558, in train
    wandb_session.watch(
  File "/home/sml161/miniconda3/envs/opso091/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 331, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sml161/miniconda3/envs/opso091/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2494, in watch
    wandb.watch(models, criterion, log, log_freq, idx, log_graph)
  File "/home/sml161/miniconda3/envs/opso091/lib/python3.10/site-packages/wandb/sdk/wandb_watch.py", line 103, in watch
    graph = wandb.run._torch.hook_torch(model, criterion, graph_idx=global_idx)
  File "/home/sml161/miniconda3/envs/opso091/lib/python3.10/site-packages/wandb/wandb_torch.py", line 321, in hook_torch
    graph.hook_torch_modules(model, criterion, graph_idx=graph_idx)
  File "/home/sml161/miniconda3/envs/opso091/lib/python3.10/site-packages/wandb/wandb_torch.py", line 376, in hook_torch_modules
    raise ValueError(
ValueError: You can only call `wandb.watch` once per model.  Pass a new instance of the model if you need to call wandb.watch again in your code.
```

**Comment by sammlapp** [comment]
This seems to be caused by using log_graph=(True) in wandb.watch().

**Comment by sammlapp** [comment]
resolved by #808
